version: '3'
services:
  bdd:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: eni
      MYSQL_DATABASE: enibdd
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - bdd:/var/lib/mysql

volumes:
  bdd:
